// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArBGwa_mmFeka6ZX8KfajH7kKTfoJN6ZU',
    appId: '1:153825310991:web:d71261b76ec62c07fb667a',
    messagingSenderId: '153825310991',
    projectId: 'fir-fluuter-codelab-f5de1',
    authDomain: 'fir-fluuter-codelab-f5de1.firebaseapp.com',
    storageBucket: 'fir-fluuter-codelab-f5de1.firebasestorage.app',
    measurementId: 'G-JH8QX0RJ1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCx-oo1qo-ZEg02g1s5L1I5Z4IBsXrcZY',
    appId: '1:153825310991:android:22ea0b05d1bd92aefb667a',
    messagingSenderId: '153825310991',
    projectId: 'fir-fluuter-codelab-f5de1',
    storageBucket: 'fir-fluuter-codelab-f5de1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDWYbIzE7hO6KuSo38Ui9n96VoQa0ZAs',
    appId: '1:153825310991:ios:19e6eec8b42f0560fb667a',
    messagingSenderId: '153825310991',
    projectId: 'fir-fluuter-codelab-f5de1',
    storageBucket: 'fir-fluuter-codelab-f5de1.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDDWYbIzE7hO6KuSo38Ui9n96VoQa0ZAs',
    appId: '1:153825310991:ios:19e6eec8b42f0560fb667a',
    messagingSenderId: '153825310991',
    projectId: 'fir-fluuter-codelab-f5de1',
    storageBucket: 'fir-fluuter-codelab-f5de1.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
